services:
  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - lifeai_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}  
    ports:
      - "5434:5432"

  backapp:
    container_name: back_django
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    environment:
      - DB_ENGINE=${DB_ENGINE}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - LM_API_URL=${LM_API_URL}
      - LM_API_MODEL=${LM_API_MODEL}
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  lifeai_db: