# Generated by Django 5.2.1 on 2025-11-13 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(db_column='classificacao', max_length=100)),
                ('dica_imc', models.TextField(db_column='dica')),
            ],
            options={
                'db_table': 'dica',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='compromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_column='titulo', max_length=200)),
                ('data', models.DateField(db_column='data')),
                ('hora_inicio', models.TimeField(db_column='hora_inicio')),
                ('hora_fim', models.TimeField(db_column='hora_fim')),
                ('concluido', models.BooleanField(db_column='concluido', default=False)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compromisso',
                'ordering': ['-data', 'hora_inicio'],
                'unique_together': {('id_usuario', 'data', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='CompromissoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(db_column='descricao')),
                ('done', models.BooleanField(db_column='done', default=False)),
                ('compromisso', models.ForeignKey(db_column='id_compromisso', on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.compromisso')),
            ],
            options={
                'db_table': 'compromisso_atividade',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='imc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField(db_column='data_consulta')),
                ('idade', models.IntegerField(db_column='idade')),
                ('sexo', models.CharField(db_column='sexo', max_length=10)),
                ('peso', models.FloatField(db_column='peso')),
                ('altura', models.FloatField(db_column='altura')),
                ('imc_res', models.FloatField(blank=True, db_column='imc_res', null=True)),
                ('classificacao', models.CharField(blank=True, db_column='classificacao', max_length=30, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imc',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='imc_user_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='nome', max_length=10)),
                ('idade', models.IntegerField(db_column='idade')),
                ('peso', models.FloatField(db_column='peso')),
                ('altura', models.FloatField(db_column='altura')),
                ('sexo', models.CharField(db_column='sexo', max_length=10)),
                ('imc_res', models.FloatField(blank=True, db_column='imc_res', null=True)),
                ('classificacao', models.CharField(blank=True, db_column='classificacao', max_length=30, null=True)),
                ('objetivo', models.CharField(db_column='objetivo', max_length=200)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imc_user_base',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='pontuacao_compromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_total_atv', models.PositiveIntegerField(db_column='qtd_total_atv', default=0)),
                ('qtd_atv_done', models.PositiveIntegerField(db_column='qtd_atv_done', default=0)),
                ('porcentagem', models.FloatField(db_column='porcentagem', default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('compromisso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pontuacao', to='core.compromisso')),
            ],
            options={
                'db_table': 'pontuacao_compromisso',
                'ordering': ['id'],
            },
        ),
    ]
