# Generated by Django 5.2.1 on 2025-11-20 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposicaoCorporal',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('data_consulta', models.DateField(auto_now_add=True, db_column='data_consulta')),
                ('gordura_percentual', models.FloatField(blank=True, db_column='gordura_percentual', null=True)),
                ('musculo_percentual', models.FloatField(blank=True, db_column='musculo_percentual', null=True)),
                ('agua_percentual', models.FloatField(blank=True, db_column='agua_percentual', null=True)),
                ('gordura_visceral', models.IntegerField(blank=True, db_column='gordura_visceral', null=True)),
                ('estimado', models.BooleanField(db_column='estimado', default=False)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'composicao_corporal',
                'ordering': ['-data_consulta'],
            },
        ),
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='titulo', max_length=200)),
                ('data', models.DateField(db_column='data')),
                ('hora_inicio', models.TimeField(db_column='hora_inicio')),
                ('hora_fim', models.TimeField(db_column='hora_fim')),
                ('concluido', models.BooleanField(db_column='concluido', default=False)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compromisso',
                'ordering': ['-data', 'hora_inicio'],
                'unique_together': {('id_usuario', 'data', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='CompromissoAtividade',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('descricao', models.TextField(db_column='descricao')),
                ('done', models.BooleanField(db_column='done', default=False)),
                ('compromisso', models.ForeignKey(db_column='id_compromisso', on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.compromisso')),
            ],
            options={
                'db_table': 'compromisso_atividade',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_column='data_criacao')),
                ('plano_alimentar', models.JSONField(db_column='plano_alimentar')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='dietas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dieta',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nome', max_length=100)),
                ('sexo', models.CharField(db_column='sexo', max_length=10)),
                ('idade', models.IntegerField(db_column='idade')),
                ('objetivo', models.CharField(db_column='objetivo', max_length=200)),
                ('restricoes_alimentares', models.TextField(blank=True, db_column='restricoes_alimentares', help_text='Ex: Intolerância a lactose, Vegano', null=True)),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfil_usuario',
            },
        ),
        migrations.CreateModel(
            name='PontuacaoCompromisso',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('qtd_total_atv', models.PositiveIntegerField(db_column='qtd_total_atv', default=0)),
                ('qtd_atv_done', models.PositiveIntegerField(db_column='qtd_atv_done', default=0)),
                ('porcentagem', models.FloatField(db_column='porcentagem', default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('compromisso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pontuacao', to='core.compromisso')),
            ],
            options={
                'db_table': 'pontuacao_compromisso',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RegistroCorporal',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('data_consulta', models.DateField(db_column='data_consulta')),
                ('peso', models.FloatField(db_column='peso')),
                ('altura', models.FloatField(db_column='altura')),
                ('imc_res', models.FloatField(blank=True, db_column='imc_res', null=True)),
                ('classificacao', models.CharField(blank=True, db_column='classificacao', max_length=30, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registro_corporal',
                'ordering': ['id'],
            },
        ),
    ]
