# Generated by Django 5.2.1 on 2025-11-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='observacao_saude',
            field=models.TextField(blank=True, db_column='observacao_saude', help_text='Ex: Asma, problema no joelho, hérnia, limitação para exercícios', null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='restricoes_alimentares',
            field=models.TextField(blank=True, db_column='restricoes_alimentares', help_text='Ex: Intolerância à lactose, Vegano', null=True),
        ),
    ]
