# Generated by Django 5.2.1 on 2025-11-16 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposicaoCorporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField(auto_now_add=True, db_column='data_consulta')),
                ('gordura_percentual', models.FloatField(blank=True, db_column='gordura_percentual', null=True)),
                ('musculo_percentual', models.FloatField(blank=True, db_column='musculo_percentual', null=True)),
                ('agua_percentual', models.FloatField(blank=True, db_column='agua_percentual', null=True)),
                ('gordura_visceral', models.IntegerField(blank=True, db_column='gordura_visceral', null=True)),
                ('estimado', models.BooleanField(db_column='estimado', default=False)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'composicao_corporal',
                'ordering': ['-data_consulta'],
            },
        ),
    ]
