# Generated by Django 5.2.1 on 2025-10-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dica',
            name='classificacao',
            field=models.CharField(db_column='classificacao', max_length=100),
        ),
    ]
