# Generated by Django 5.2.1 on 2025-11-22 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilusuario_observacao_saude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoExercicio',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nome_exercicio', models.CharField(db_column='nome_exercicio', max_length=150)),
                ('duracao_segundos', models.PositiveIntegerField(db_column='duracao_segundos')),
                ('calorias_queimadas', models.PositiveIntegerField(db_column='calorias_queimadas')),
                ('data_treino', models.DateTimeField(db_column='data_treino')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historico_exercicio',
                'ordering': ['-data_treino'],
            },
        ),
    ]
