# Generated by Django 5.2.1 on 2025-11-20 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_composicaocorporal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_column='data_criacao')),
                ('plano_alimentar', models.JSONField(db_column='plano_alimentar')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='dietas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dieta',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nome', max_length=100)),
                ('sexo', models.CharField(db_column='sexo', max_length=10)),
                ('idade', models.IntegerField(db_column='idade')),
                ('objetivo', models.CharField(db_column='objetivo', max_length=200)),
                ('restricoes_alimentares', models.TextField(blank=True, db_column='restricoes_alimentares', help_text='Ex: Intolerância a lactose, Vegano', null=True)),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfil_usuario',
            },
        ),
        migrations.CreateModel(
            name='PontuacaoCompromisso',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('qtd_total_atv', models.PositiveIntegerField(db_column='qtd_total_atv', default=0)),
                ('qtd_atv_done', models.PositiveIntegerField(db_column='qtd_atv_done', default=0)),
                ('porcentagem', models.FloatField(db_column='porcentagem', default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pontuacao_compromisso',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RegistroCorporal',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('data_consulta', models.DateField(db_column='data_consulta')),
                ('peso', models.FloatField(db_column='peso')),
                ('altura', models.FloatField(db_column='altura')),
                ('imc_res', models.FloatField(blank=True, db_column='imc_res', null=True)),
                ('classificacao', models.CharField(blank=True, db_column='classificacao', max_length=30, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registro_corporal',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='dica',
        ),
        migrations.RemoveField(
            model_name='imc_user_base',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='pontuacao_compromisso',
            name='compromisso',
        ),
        migrations.AlterField(
            model_name='composicaocorporal',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='composicaocorporal',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compromissoatividade',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pontuacaocompromisso',
            name='compromisso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pontuacao', to='core.compromisso'),
        ),
        migrations.DeleteModel(
            name='imc',
        ),
        migrations.DeleteModel(
            name='imc_user_base',
        ),
        migrations.DeleteModel(
            name='pontuacao_compromisso',
        ),
    ]
