apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: lifeai
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 88
      targetPort: 88
  type: LoadBalancer