# Example secret template (do not use in production)
apiVersion: v1
kind: Secret
metadata:
  name: lifeai-secrets
  namespace: lifeai
type: Opaque
data:
  POSTGRES_USER: ZmFrZV91c2Vy    # fake_user
  POSTGRES_PASSWORD: ZmFrZV9wYXNz  # fake_pass
  DB_USER: ZmFrZV91c2Vy           # fake_user
  DB_PASSWORD: ZmFrZV9wYXNz       # fake_pass
  DJANGO_SECRET_KEY: ZmFrZV9kamFuZ29fc2VjcmV0X2tleQ==  # fake_django_secret_key
  PGADMIN_DEFAULT_EMAIL: ZmFrZUBleGFtcGxlLmNvbQ==      # fake@example.com
  PGADMIN_DEFAULT_PASSWORD: ZmFrZV9wYXNzMTIz           # fake_pass123
  GEMINI_API_KEY: RkFLRV9HRU1JTklfS0VZX0VYQU1QTEU=     # FAKE_GEMINI_KEY_EXAMPLE
